### ISSUE TITLE
cibersort can not run

### ISSUE THREAD

**Issue by liuxy9797** [omnideconv/immunedeconv#79] opened 2021-11-08 12:26 UTC
This error occurs when I run it, but otherwise works fine.

> res  <-deconvolute(exprMatrix, "cibersort") 

>>> Running cibersort
Error in (function (sig_matrix, mixture_file, perm = 0, QN = TRUE)  : 
  Parameter useless(absolute = FALSE, abs_method = "sig.score")

**Comment by grst** [comment] 2022-04-29 19:09
Hi @liuxy9797, 

sorry for not following up earlier. Does this issue persist? 
If yes, can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) with example data?

**Comment by Gorgot** [comment] 2022-05-12 12:35
I have the same problem. My expression matrix can run quanriseq well in immunedeconv, but not cibersort.
Here's the error dialog:

Error in (function (sig_matrix, mixture_file, perm = 0, QN = TRUE)  : 
  unused arguments (absolute = FALSE, abs_method = "sig.score")

**Comment by grst** [comment] 2022-05-12 18:58
I'm starting to wonder if you might have a different version of the `CIBERSORT.R` script. 

Could you send me your `CIBERSORT.R` script by e-mail (do NOT post it here due to the licensing)? My email can be found on my github profile.

**Comment by Gorgot** [comment] 2022-05-14 00:43
Thank you for your reply! I did use a wrong version of CIBERSORT.R script of v1.03. Now the issue has been settled by v1.04. By the way, may I ask which version of script is required for immunedeconv?

**Comment by grst** [comment] 2022-05-14 18:04
I wasn't even aware there were multiple versions. I have been using v1.04. 
We should probably add a check for this.

**Comment by Gorgot** [comment] 2022-05-14 23:31
Thanks for your efforts!

**Comment by harratabi** [comment] 2024-01-31 00:46
How do you get v1.04? I requested the CIBERSORT R script and was approved, but the version I download is V1.02 and I don't see any other links.

**Comment by grst** [comment] 2024-01-31 10:11
closing in favor of https://github.com/omnideconv/immunedeconv/issues/137

**Closed by grst** 2024-01-31 10:11 UTC
Labels: bug

**Comment by dfeng4127** [comment] 2024-07-26 02:23
Hi when i run :
results <- cibersort('./type_use.txt', "./exp_sp.txt") 

I got this error:
Error in (function (.x, .f, ..., .progress = FALSE)  : 
  ℹ In index: 1.
Caused by error in `predict.svm()`:
! Model is empty!

**Comment by LorenzoMerotto** [comment] 2024-07-26 07:50
Hello @dfeng4127 

`cibersort()` is not a function included in immunedeconv. 
Could you please try to apply the `deconvolute_cibersort()` function and include the error message here?
