### ISSUE TITLE
Error in deconvolute_cibersort

### ISSUE THREAD

**Issue by anyang-kevin** [omnideconv/immunedeconv#142] opened 2023-03-30 08:41 UTC
It's same as question #60 
When running `deconvolute_cibersort`, error is:
`assertion failed: CIBERSORT.R is provided
Error: exists("cibersort_binary", envir = config_env) is not TRUE`
How to fix it?
The old link in question 60 is no longer valid.
Thanks for your help.

**Comment by grst** [comment] 2023-03-30 08:42
Sorry about that. The new link is https://omnideconv.org/immunedeconv/articles/immunedeconv.html#special-case-cibersort

**Comment by anyang-kevin** [comment] 2023-03-30 09:00
Thanks!
I found another bug from quantiseq. I provide a matrix without repeat gene symbol.But in quantiseq method, an error occurs in the reannotation step. The rownames will be repeated causing the rowname to not be changed and error. I think it may happend in quantiseq- function mapGenes.
I found that repetition comes from gene "NCRNA00250"
Then I change the annotation file "HGNC_genenames_20170418.txt" and my matrix, deleted this gene. The program is running normally.
I'm not sure why this problem has arisen. This gene is not duplicated in my matrix or annotation file. Maybe you could try to figure out why.If you need my exp matrix, I will be happy to provide it, please send me the email address to send the file.

**Comment by grst** [comment] 2023-04-03 05:41
Hi, 

I'll take a look. My e-mail address should be visible in my github profile. Could you please also provide the code snippet you are running when this error occurs?

**Comment by anyang-kevin** [comment] 2023-04-07 05:39
Hi,
The file has been sent to your email address.
Hope for your reply.
Thank you.

**Comment by grst** [comment] 2023-04-17 07:19
Hi @anyang-kevin, 

I received your files, but I cannot reproduce your error. 

Here's what I ran (using immunedeconv freshly installed from github): 
```r
library(immunedeconv)
df <- read.csv('TCGA-SARC.test.txt',sep='\t',header = TRUE)
df <- df[!duplicated(df$Gene.symbol),]
rownames(df) <- df[,1]
df <- df[,-1]
df$mean <- apply(df,1,mean)
df <- df[df$mean > 0.1,]
res <- deconvolute(df, method="quantiseq")
```
```
r$> res
# A tibble: 11 × 11
   cell_type                    TCGA.HB.A43Z TCGA.DX.A8BG TCGA.3B.A9HU TCGA.PC.A5DL TCGA.DX.AB32 TCGA.DX.A7EM TCGA.X6.A8C5 TCGA.DX.A3UF TCGA.DX.A7EL   mean
   <chr>                               <dbl>        <dbl>        <dbl>        <dbl>        <dbl>        <dbl>        <dbl>        <dbl>        <dbl>  <dbl>
 1 B cell                             0.0677       0.120        0.117        0.0693     1.73e- 1       0.0663       0.0899      0.0599        0.0996 0.0986
 2 Macrophage M1                      0.0183       0.0535       0.0479       0.0323     4.88e- 2       0.0413       0.0284      0.0416        0.0381 0.0392
 3 Macrophage M2                      0.144        0.214        0.148        0.117      2.52e- 1       0.132        0.195       0.144         0.158  0.169 
 4 Monocyte                           0.0291       0.0221       0.0561       0.0528     1.48e- 2       0            0.0903      0.00716       0.0364 0.0381
 5 Neutrophil                         0.0397       0.0424       0.0236       0.0326     4.90e- 2       0.0635       0.0221      0.0305        0.0408 0.0385
 6 NK cell                            0.0621       0.0401       0.0495       0.0393     3.57e- 2       0.0431       0.0502      0.0562        0.0449 0.0475
 7 T cell CD4+ (non-regulatory)       0            0            0.0569       0.253      0              0.146        0.0923      0.189         0      0.0656
 8 T cell CD8+                        0.0696       0.225        0.148        0.0644     1.56e- 1       0.0795       0.135       0.0669        0.181  0.130 
 9 T cell regulatory (Tregs)          0.0826       0.220        0.202        0.0552     2.35e- 1       0.100        0.105       0.0534        0.177  0.148 
10 Myeloid dendritic cell             0.0637       0.0621       0.0327       0.0361     3.57e- 2       0.0494       0.0286      0.0589        0.0325 0.0450
11 uncharacterized cell               0.423        0            0.119        0.248      1.11e-16       0.279        0.164       0.293         0.192  0.181 
```

**Comment by grst** [comment] 2023-10-19 20:26
Closing this for now, let us know if there are still any issues.

**Closed by grst** 2023-10-19 20:26 UTC
Labels: bug
